In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

### Data exploration

In [2]:
# Load data
df = pd.read_csv("2020_MX_Region_Mobility_Report.csv", encoding='cp1252')

In [3]:
df

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,MX,Mexico,NaN,NaN,NaN,NaN,NaN,2020-02-15,6,4,6,4.0,3,-1
1,MX,Mexico,NaN,NaN,NaN,NaN,NaN,2020-02-16,7,6,7,6.0,2,-1
2,MX,Mexico,NaN,NaN,NaN,NaN,NaN,2020-02-17,2,4,3,5.0,11,-2
3,MX,Mexico,NaN,NaN,NaN,NaN,NaN,2020-02-18,0,-1,3,2.0,9,-2
4,MX,Mexico,NaN,NaN,NaN,NaN,NaN,2020-02-19,0,0,2,3.0,8,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9136,MX,Mexico,Zacatecas,NaN,NaN,MX-ZAC,NaN,2020-11-13,-34,-6,-45,-34.0,-25,10
9137,MX,Mexico,Zacatecas,NaN,NaN,MX-ZAC,NaN,2020-11-14,-29,-2,-35,-27.0,0,5
9138,MX,Mexico,Zacatecas,NaN,NaN,MX-ZAC,NaN,2020-11-15,-26,-3,-34,-35.0,1,4
9139,MX,Mexico,Zacatecas,NaN,NaN,MX-ZAC,NaN,2020-11-16,-31,-1,-41,-37.0,-46,12
9140,MX,Mexico,Zacatecas,NaN,NaN,MX-ZAC,NaN,2020-11-17,-34,-9,-46,-31.0,-29,9

In [4]:
df = df.rename(columns={'retail_and_recreation_percent_change_from_baseline': 'Retail', 'grocery_and_pharmacy_percent_change_from_baseline': 'Grocery', 'parks_percent_change_from_baseline':'Parks', 'transit_stations_percent_change_from_baseline':'Transit', 'workplaces_percent_change_from_baseline':'Workplaces', 'residential_percent_change_from_baseline':'Residential'})
df

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,date,Retail,Grocery,Parks,Transit,Workplaces,Residential
0,MX,Mexico,NaN,NaN,NaN,NaN,NaN,2020-02-15,6,4,6,4.0,3,-1
1,MX,Mexico,NaN,NaN,NaN,NaN,NaN,2020-02-16,7,6,7,6.0,2,-1
2,MX,Mexico,NaN,NaN,NaN,NaN,NaN,2020-02-17,2,4,3,5.0,11,-2
3,MX,Mexico,NaN,NaN,NaN,NaN,NaN,2020-02-18,0,-1,3,2.0,9,-2
4,MX,Mexico,NaN,NaN,NaN,NaN,NaN,2020-02-19,0,0,2,3.0,8,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9136,MX,Mexico,Zacatecas,NaN,NaN,MX-ZAC,NaN,2020-11-13,-34,-6,-45,-34.0,-25,10
9137,MX,Mexico,Zacatecas,NaN,NaN,MX-ZAC,NaN,2020-11-14,-29,-2,-35,-27.0,0,5
9138,MX,Mexico,Zacatecas,NaN,NaN,MX-ZAC,NaN,2020-11-15,-26,-3,-34,-35.0,1,4
9139,MX,Mexico,Zacatecas,NaN,NaN,MX-ZAC,NaN,2020-11-16,-31,-1,-41,-37.0,-46,12
9140,MX,Mexico,Zacatecas,NaN,NaN,MX-ZAC,NaN,2020-11-17,-34,-9,-46,-31.0,-29,9

In [5]:
# Select data for states
from datetime import datetime
df = pd.read_csv("2020_MX_Region_Mobility_Report.csv", encoding='cp1252')
df = df.rename(columns={'retail_and_recreation_percent_change_from_baseline': 'Retail', 'grocery_and_pharmacy_percent_change_from_baseline': 'Grocery', 'parks_percent_change_from_baseline':'Parks', 'transit_stations_percent_change_from_baseline':'Transit', 'workplaces_percent_change_from_baseline':'Workplaces', 'residential_percent_change_from_baseline':'Residential'})
edos = df[df.sub_region_1.notnull()]
edos

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,date,Retail,Grocery,Parks,Transit,Workplaces,Residential
277,MX,Mexico,Aguascalientes,NaN,NaN,MX-AGU,NaN,2020-02-15,7,6,6,-14.0,4,-2
278,MX,Mexico,Aguascalientes,NaN,NaN,MX-AGU,NaN,2020-02-16,9,7,5,1.0,1,-1
279,MX,Mexico,Aguascalientes,NaN,NaN,MX-AGU,NaN,2020-02-17,1,2,0,-5.0,12,-2
280,MX,Mexico,Aguascalientes,NaN,NaN,MX-AGU,NaN,2020-02-18,0,-3,3,-4.0,10,-2
281,MX,Mexico,Aguascalientes,NaN,NaN,MX-AGU,NaN,2020-02-19,-1,-2,-2,-2.0,9,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9136,MX,Mexico,Zacatecas,NaN,NaN,MX-ZAC,NaN,2020-11-13,-34,-6,-45,-34.0,-25,10
9137,MX,Mexico,Zacatecas,NaN,NaN,MX-ZAC,NaN,2020-11-14,-29,-2,-35,-27.0,0,5
9138,MX,Mexico,Zacatecas,NaN,NaN,MX-ZAC,NaN,2020-11-15,-26,-3,-34,-35.0,1,4
9139,MX,Mexico,Zacatecas,NaN,NaN,MX-ZAC,NaN,2020-11-16,-31,-1,-41,-37.0,-46,12
9140,MX,Mexico,Zacatecas,NaN,NaN,MX-ZAC,NaN,2020-11-17,-34,-9,-46,-31.0,-29,9

In [6]:
# Extract state names
edo_names = edos['sub_region_1'].unique()
edo_names

array(['Aguascalientes', 'Baja California', 'Baja California Sur',
       'Campeche', 'Chiapas', 'Chihuahua', 'Coahuila', 'Colima',
       'Durango', 'Guanajuato', 'Guerrero', 'Hidalgo', 'Jalisco',
       'Mexico City', 'MichoacÃƒÂ¡n', 'Morelos', 'Nayarit', 'Nuevo Leon',
       'Oaxaca', 'Puebla', 'QuerÃƒÂ©taro', 'Quintana Roo',
       'San Luis Potosi', 'Sinaloa', 'Sonora', 'State of Mexico',
       'Tabasco', 'Tamaulipas', 'Tlaxcala', 'Veracruz', 'Yucatan',
       'Zacatecas'], dtype=object)

In [7]:
# Select only residential data
edos = edos[['date','sub_region_1','Residential']]
edos['date']=pd.to_datetime(edos['date'])
edos

<ipython-input-7-383d158ba852>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  edos['date']=pd.to_datetime(edos['date'])

           date    sub_region_1  Residential
277  2020-02-15  Aguascalientes           -2
278  2020-02-16  Aguascalientes           -1
279  2020-02-17  Aguascalientes           -2
280  2020-02-18  Aguascalientes           -2
281  2020-02-19  Aguascalientes           -1
...         ...             ...          ...
9136 2020-11-13       Zacatecas           10
9137 2020-11-14       Zacatecas            5
9138 2020-11-15       Zacatecas            4
9139 2020-11-16       Zacatecas           12
9140 2020-11-17       Zacatecas            9

[8864 rows x 3 columns]

In [8]:
## Make a time series for each state
series = []
for edo in edo_names:
    serie = edos[edos['sub_region_1']==edo]
    serie = serie[['date','Residential']]
    serie.set_index('date',inplace=True)
    ts = serie['Residential']
    series.append(ts)

### Exercise

- Use the method Ward with Euclidean distance to find 5 clusters.

- Plot the dendogram

- At which distance you must cut off for finding the 5 clusters?

- Using the method Single with the metrics: Pearson Correlation, Spearman Correlation and Dynamic Time Warpping

- Plot the 3 dendograms

- On each one of the last three clusterings using the single method, which are the 3 states with the oddest behavior (more different from the rest).

- Which of the 4 clustering configurations provide the most balanced distribution, i.e. where the clusters have approximately the same number of states.